version: "3.9"

services:
  poker-api:
    build:
      context: ./backend
    container_name: poker-api
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"        # FastAPI/Flask/Socket.IO backend
    volumes:
      - ./backend:/app
    command: >
      sh -c "python3 server.py"
    networks:
      - poker-net

  poker-expo:
    build:
      context: ./PokerAppFrontend
      args:
        # 👇 set this to your host machine LAN IP (compose passes env below)
        HOST_IP: ${HOST_IP}
    container_name: poker-expo
    environment:
      # same value available at runtime
      REACT_NATIVE_PACKAGER_HOSTNAME: ${HOST_IP}
      EXPO_DEV_SERVER_PORT: 8081
      EXPO_USE_METRO_WORKSPACE_ROOT: "1"
      WATCHPACK_POLLING: "true"
      # pass your API url to the app
      API_URL: http://${HOST_IP}:5000
    ports:
      - "8081:8081"     # Metro/Dev Server
      - "19006:19006"   # Expo web
      - "19000:19000"   # Legacy Expo Go (Android)
      - "19001:19001"   # Legacy Expo Go (iOS)
    volumes:
      - ./PokerAppFrontend:/app
      - /app/node_modules
    command: >
      sh -c "npx expo start --host lan --port 8081 --web-port 19006 --clear"
    networks:
      - poker-net

networks:
  poker-net:
    driver: bridge
